project:
  type: website
  output-dir: ../_site/

website:
  title: "MUIC case study"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/ngiangre/rflp_muic_data
        aria-label: GitHub

format:
  html:
    theme: pulse
    toc: true